const ActionType = {
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  SET_AUTH: `SET_AUTH`,
  ADD_FILM: `ADD_FILM`,
  REMOVE_FILM: `REMOVE_FILM`,
  INIT_MY_LIST_FILM: `INIT_MY_LIST_FILM`
};

export default ActionType;
