const ActionType = {
  SET_LOADING: `SET_LOADING`,
  SET_ERROR: `SET_ERROR`,
  SET_GENRE_FILTER: `SET_GENRE_FILTER`,
  SET_FILMS_PER_PAGE: `SET_FILMS_PER_PAGE`,
  RESET_FILMS_PER_PAGE: `RESET_FILMS_PER_PAGE`,
  LOAD_FILMS: `LOAD_FILMS`,
  UPDATE_IS_FAVORITE_STATUS: `UPDATE_IS_FAVORITE_STATUS`
};

export default ActionType;
